### ISSUE TITLE
It Crash when i go to the page selected

### ISSUE THREAD

**Issue by CrisMon-01** [jlandersen/xamarin-forms-camera#2]
It compile but when i go to this page,the page ,where there is the fab that had to call all the stuff with the binding it crash
@jlandersen 

`using Sport.Pagine.Login;
using Sport.Services;
using Sport.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Xamarin.Forms;
using Xamarin.Forms.Xaml;

namespace Sport.Pagine
{
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Account : ContentPage
    {
        public User Current { get; set; }

        public Account()
        {
            NavigationPage.SetHasNavigationBar(this, false);

            Current = App.CredentialsService.GetCurrentUser();

            BindingContext = Current;

            InitializeComponent();

            BindingContext = new TakePictureViewModel(DependencyService.Get<ICameraProvider>()); ;
            
        }

        private async Task OnDeleteAccount(object sender, EventArgs e)
        {

            if (!DatabaseManager.IsOnline())
                await DisplayAlert("No connection", "Impossible to delete the account", "Ok");
            else
            {
                var answer = await DisplayAlert("Are you sure you want to delete your account?", "All your items and settings will be permanently deleted", "Yes", "No");

                if (answer)
                {
                    var items = await DatabaseManager.DefaultManager.GetItemsAsync("allItems");

                    foreach (var i in items)
                    {
                        if (i.UserId.Equals(App.CredentialsService.Id))
                            await DatabaseManager.DefaultManager.DeleteTaskAsync(i);
                    }

                    await DatabaseManager.DefaultManager.DeleteUserParticipations(Current);

                    await DatabaseManager.DefaultManager.DeleteUserAsync(Current);

                    await DisplayAlert("Account deleted", "Now you will be logged out", "OK");

                    MasterDetailPage1.OnLogoutButtonClicked();
                }
            }
            
        }

        private async Task OnSaveChanges(object sender, EventArgs e)
        {

            if (!DatabaseManager.IsOnline())
                await DisplayAlert("No connection", "Impossible to delete the account", "Ok");
            else
            {
                //Current.Name = entryName.Text;
                //Current.Email = entryEmail.Text;

                await DatabaseManager.DefaultManager.InsertUserAsync(Current);

                App.CredentialsService.DeleteCredentials();

                App.CredentialsService.SaveCredentials(Current);

                await DisplayAlert("Settings saved", "Your settings have been saved", "OK");

                await Navigation.PopAsync();
            }

        }
    }
}`
`<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:fab="clr-namespace:Refractored.FabControl;assembly=Refractored.FabControl"
             xmlns:controls="clr-namespace:ImageCircle.Forms.Plugin.Abstractions;assembly=ImageCircle.Forms.Plugin.Abstractions"
             x:Class="Sport.Pagine.Account">
    <ContentPage.Content>
        <StackLayout>
            <Grid HeightRequest="200">
                <Image Source="bg7.png" HorizontalOptions="Fill" VerticalOptions="Fill" Aspect="AspectFill" />
                <Grid Padding="15,15">
                    <StackLayout>
                        <controls:CircleImage Source="{Binding Picture}" WidthRequest="65" HeightRequest="65" Aspect="AspectFit" HorizontalOptions="CenterAndExpand" VerticalOptions="Start"/>
                        <Label Text="{Binding Name}" Style="{DynamicResource TitleStyle}" HorizontalTextAlignment="Center" HorizontalOptions="CenterAndExpand" FontAttributes="Bold" FontSize="20" TextColor="White" VerticalOptions="End"/>
                        <Label Text="{Binding Email}" Style="{DynamicResource TitleStyle}" HorizontalTextAlignment="Center" HorizontalOptions="CenterAndExpand" TextColor="AliceBlue" FontSize="18" VerticalOptions="End"/>
                        <fab:FloatingActionButtonView
				            ImageName="camera.png"
				            x:Name="FloatingActionButtonAdd"
                            ColorNormal="Transparent"
                            ColorPressed="Transparent"
				            ColorRipple="Transparent"
                            IsVisible="True"
                            HorizontalOptions="End"/>
                    </StackLayout>
                </Grid>
            </Grid>
            <StackLayout Padding="10" Margin="5" Orientation="Horizontal">
                <Image Source="profile.png" HorizontalOptions="Start" VerticalOptions="CenterAndExpand" HeightRequest="25"/>
                <Entry x:Name="entryName" Placeholder="Title" Text="{Binding Name}" FontSize="Medium" HorizontalOptions="FillAndExpand" VerticalOptions="CenterAndExpand" />
            </StackLayout>
            <Label Text="Email" FontSize="Small" HorizontalOptions="Center" />
            <StackLayout Padding="10" Margin="5" Orientation="Horizontal">
                <Image Source="mail.jpg" HorizontalOptions="Start" VerticalOptions="CenterAndExpand" HeightRequest="25"/>
                <Entry x:Name="entryEmail" Placeholder="Title" Text="{Binding Email}" FontSize="Medium" HorizontalOptions="FillAndExpand" VerticalOptions="CenterAndExpand"/>
            </StackLayout>
            
            <StackLayout VerticalOptions="Center" Margin="20">
                <Button Text="SAVE CHANGES" BackgroundColor="Blue" TextColor="White" FontSize="Medium" HorizontalOptions="Center" VerticalOptions="Center" Clicked="OnSaveChanges"/>
            </StackLayout>
            <StackLayout VerticalOptions="Center" Margin="20">
                <Button Text="DELETE ACCOUNT" BackgroundColor="Crimson" TextColor="White" FontSize="Medium" HorizontalOptions="Center" VerticalOptions="Center" Clicked="OnDeleteAccount"/>
            </StackLayout>
        </StackLayout>
    </ContentPage.Content>
</ContentPage>
`

**Comment by jlandersen** [comment]
Hi

Sorry to hear about the issues. I haven't worked with Xamarin in the past 3 years, and the code targeted a much older version, so I can't say I am surprised some issues are appearing with 3 years of changes to the Xamarin platform. Would you be interested in trying to resolve it and make a PR?
