### ISSUE TITLE
Xamarin.android

### ISSUE THREAD

**Issue by sagarmp02** [jlandersen/xamarin-forms-camera#3]
I need to implement auto capture image without user interaction after some seconds. help me
![lrfit](https://user-images.githubusercontent.com/37401688/37519030-b507b8d0-293d-11e8-9b8f-e06276351157.png)

**Comment by jlandersen** [comment]
Hi

I haven't touched Xamarin in several years - I would suggest either stackoverflow or https://forums.xamarin.com/ for such a question.
